# Generated by Django 5.2.8 on 2025-11-19 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fraud", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fraudalert",
            old_name="transaction",
            new_name="transaction_id",
        ),
    ]
