# Generated by Django 5.2.8 on 2025-11-19 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fraud", "0002_rename_transaction_fraudalert_transaction_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fraudalert",
            old_name="transaction_id",
            new_name="transaction",
        ),
    ]
