version: '3.8'

services:
  web:
    build: .
    image: capitec-assessment-service:latest
    ports:
      - "8000:8000"
    environment:
      - RUN_MIGRATIONS=1
      - COLLECT_STATIC=1
      - WAIT_FOR_DB=0
    volumes:
      - ./:/app:delegated
    restart: unless-stopped
